---
- hosts: all
  become: true
  tasks:
    - name: Upgrade all packages 
      yum: 
        name: '*'
        state: latest

    - name: add Node.js repo
      shell: "curl -sL https://rpm.nodesource.com/setup_10.x | bash -"

    - name: Install Node.js
      yum:
        name: nodejs
        state: latest

    # - name: add Yarn repo
    #   shell: "curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo"

    # - name: Install Yarn
    #   yum:
    #     name: yarn
    #     state: latest

    - name: add MongoDB repo
      blockinfile:
        path: /etc/yum.repos.d/mongodb-org-4.0.repo
        insertafter: EOF
        create: yes
        state: present
        block: |
          {{ "[mongodb-org-4.0]" }}
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.0.asc

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: latest

    - name: enable and start MongoDB service
      systemd:
        name: mongod
        enabled: yes
        state: started