---
- hosts: all
  become: true
  tasks:
    - name: Upgrade all packages 
      yum: 
        name: '*'
        state: latest

    - name: add docker repo
      shell: "curl -sL https://rpm.nodesource.com/setup_10.x | bash -"

    - name: Install Node.js
      yum:
        name: nodejs
        state: latest